version: '3.9'

services:
  web:
    container_name: backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - static:/app/web/staticfiles

    ports:
      - 8000:8000
    env_file:
      - ./backend/.env


  www:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - node_modules:/app/www/node_modules

    ports:
      - 3000:3000

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - static:/app/web/static
    ports:
      - 81:80


volumes:
  static:
  node_modules: