# Generated by Django 4.2.6 on 2023-11-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclipr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_slug',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
