# Generated by Django 4.2.6 on 2023-11-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclipr', '0002_alter_url_short_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='tags',
            field=models.ManyToManyField(blank=True, to='appclipr.tag'),
        ),
    ]
